version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
  - package-ecosystem: gradle
    directory: /
    schedule:
      interval: daily
    groups:
      minor-version-updates:
        applies-to: version-updates
        update-types:
          - minor
          - patch
